@isTest
public class AIA_WorkplantypeTriggerHandler_Test {

    public static testmethod void beforeDeleteTest(){
     /*  commented as per US 210
       Test.startTest();
        Account acc= AIA_TestUtil.createAccount('Test12398');
        List<Opportunity> oppList=AIA_TestUtil.createOpps(acc.id);
        AIA_TestUtil.CreateImplementation(oppList.get(0).Id);
        try{
            List<AIA_Workplan_Type__c> workplanList=[select id from AIA_Workplan_Type__c  where id in(select Workplan_Type__c from AIA_Implementation__c)];
            delete workplanList;
        }catch(DmlException e){
            
        }
         Test.stopTest();
*/
    }

    
}